name: Build (APK AAB IPA)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11
  FLUTTER_VERSION: 3.24.0

jobs:
  build-linux-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run compile
        run: |
          make compile

      - name: Flet Build APK
        run: |
          flutter config --no-analytics 
          flet build apk --verbose --no-android-splash

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Simple-apk
          path: build/apk
          if-no-files-found: error
          overwrite: true
